---
title: "Profile"
author: "Muhammad Tsany"
categories: ["R"]
tags: ["R Markdown", "profile"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

- Teaching Assistant, Kumon Math Centre
  - Aid over 30 students with pre-calculus and calculus mathematics concepts and reading comprehension
  - Oversaw development of students’ math skills and reading comprehension over several months
  - Graded and reviewed over 20 assignments effectively over an hour on a short turnaround
  
- Sales Advisor, H&M 
  - Provided high quality of customer service on sales floor to over 300 customers weekly
  - Processed customer payments at POS terminal more than $1,000 daily
  - Recommended products based on customer preferences to provide personal experience
  
- Programming Assistant, Liquid Assets Dragon Boat Team
  - Led weekly workouts for 4-10 recruits throughout a 2-hour period open to over 200 recruits
  - Praised by recruits in anonymous feedback for creating an engaging environment with detailed explanations
  - Supervised by the Head Trainer with data collection, analysis, and visualization of fitness data to improve the current workout program using R software

